---
title: "test6"
output: html_document
---

# http://jcbretal.github.io/class.coursera.org-predmachlearn-016/Prediction%20Assignment%20Writeup.html

```{r}
#load data and libraries
library(caret)
library(doMC)
registerDoMC(cores = 2)
set.seed(2)
datos = read.csv("~/Descargas/pml-training.csv")
training <- subset(datos,select=-c(X,
                                user_name,
                                raw_timestamp_part_1,
                                raw_timestamp_part_2,
                                cvtd_timestamp))

test <- read.csv("~/Descargas/pml-testing.csv")
testing <- subset(test,select=-c(X,
                                user_name,
                                raw_timestamp_part_1,
                                raw_timestamp_part_2,
                                cvtd_timestamp,
                                problem_id))

# comparative of unused columns training vs test set
nzvTrain <- nearZeroVar(training)
nzvTest <- nearZeroVar(testing)
nzvTest %in% nzvTrain

filteredTraining <- training[, -nzvTest]# removing unused columns
dim(filteredTraining)

```

```{r}
set.seed(2)
library(doMC)
# creating a partition over the training set to achieve validation set
inTrain = createDataPartition(filteredTraining$classe, p = 0.6)[[1]]
trainFit = filteredTraining[ inTrain,]
testFit = filteredTraining[-inTrain,]

# fit to random forest with preprocessing
modFit <- train( trainFit$classe ~ . ,method="rf", 
                  allowParallel=TRUE ,
                  data=trainFit , 
                  preProcess = c("center", "scale"))
print(modFit$finalModel)
```

