---
title: "Untitled"
output: html_document
---

---
title: "Practical Machine Learning - Course Project"
output: html_document
---

## Executive Summary  
One thing that people regularly do is quantify how much of a particular activity they do, but they rarely quantify how well they do it. In this project, the goal will be to use data from accelerometers on the belt, forearm, arm, and dumbell of 6 participants and predict the manner in which they did the exercise. To do this multiple models, such as randomForest, ntree, rt, cv, gbm,  were built and compared to maximize speed and accuracy.  Model "randomForest" was chosen as a final method.  

## Question  

Using data from accelerometers on the belt, forearm, arm, and dumbell of 6 participants. Participants were asked to perform barbell lifts correctly and incorrectly in 5 different ways. The question we are exploring is: can we predict the activity (class A-E) participant is most likely to perform?  

* R scripts have been produced and testing using Windows 7 and Windows 10 with R version 3.2.2 (2015-08-14),platform x86_64-w64-mingw32  

## Imput Data  
Check to see if data files exist. If they do not exist, download from website: "http://d396qusza40orc.cloudfront.net/predmachlearn/pml-training.csv"  

```{r input_data, echo=FALSE}
# Load data. Import if necessary
if (!file.exists("pml-training.csv")) {
  download.file("http://d396qusza40orc.cloudfront.net/predmachlearn/pml-training.csv", 
                destfile = "pml-training.csv")
}
if (!file.exists("pml-testing.csv")) {
  download.file("http://d396qusza40orc.cloudfront.net/predmachlearn/pml-testing.csv", 
                destfile = "pml-testing.csv")
}

# Convert NA,NULL,#DIV/0! when reading in the data
pmlTrainingSet <- read.csv("pml-training.csv", header = TRUE, sep = ",",na.strings=c('NA','','#DIV/0!'))
```

Check libraries. If libraries are not loaded, load them.  

- Library List Used

    - caret
    - randomForest
    - foreach  
    - doParallel  
    - rpart
    - rattle  

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
