```{r}
library(caret)
library(rpart)
library(rpart.plot)
library(RColorBrewer)
library(rattle)
library(randomForest)

set.seed(12345)
```
```{r}
if (!file.exists("pml-training.csv")) { 
  download.file("http://d396qusza40orc.cloudfront.net/predmachlearn/pml-training.csv",  
                destfile = "pml-training.csv") 
} 
if (!file.exists("pml-testing.csv")) { 
  download.file("http://d396qusza40orc.cloudfront.net/predmachlearn/pml-testing.csv",  
                destfile = "pml-testing.csv") 
}

pmlTrainingSet <- read.csv("pml-training.csv", header = TRUE, sep =  ",",na.strings=c('NA','','#DIV/0!')) 
pmlTestingSet <- read.csv("pml-testing.csv", header = TRUE, sep =  ",",na.strings=c('NA','','#DIV/0!'))
```

```{r}
inTrain <- createDataPartition(y=pmlTrainingSet$classe, p=0.6, list=FALSE ) 
training <- pmlTrainingSet[inTrain,] 
testing <- pmlTrainingSet[-inTrain,] 
dim(training) 
dim(testing)
```


```{r}
nsv <- nearZeroVar(training, saveMetrics = TRUE) 
```
```{r}
training <- colnames(pmlTrainingSet[colSums(is.na(training)) == 0])[-(1:7)] 

training <- training[!nsv]
dim(training)
```

