---
title: "try7"
output: html_document
---
```{r}
library(caret)
library(randomForest)
library(foreach)
library(doParallel)
library(rpart)
library(rattle)

set.seed(2048)
options(warn=-1)

pmlTrainingSet <- read.csv("pml-training.csv", header = TRUE, sep = ",",na.strings=c('NA','','#DIV/0!'))
```
```{r}
for(i in c(8:ncol(pmlTrainingSet)-1)){pmlTrainingSet[,i]=as.numeric(as.character((pmlTrainingSet[,i])))}
feature_set <- colnames(pmlTrainingSet[colSums(is.na(pmlTrainingSet)) == 0])[-(1:7)]
model_data <- pmlTrainingSet[feature_set]
feature_set
```
```{r}             
idx <- createDataPartition(y=pmlTrainingSet$classe, p=0.75, list=FALSE )
training <- model_data[idx,]
testing <- model_data[-idx,]
dim(training)
dim(testing)
```
```{r}
x <- training[-ncol(training)]
y <- training$classe

rf <- foreach(ntree=rep(150, 6), .combine=randomForest::combine, .packages='randomForest') %dopar% {randomForest(x, y, ntree=ntree)}
predictions1 <- predict(rf, newdata=training)
confusionMatrix(predictions1,training$classe)
```
```{r}
predictions2 <- predict(rf, newdata=testing)
confusionMatrix(predictions2,testing$classe)
```
```{r}
modFit <- train(classe ~ .,method="rpart",data=training)
print(modFit$finalModel)
```
```{r}
plot(modFit$finalModel,uniform=TRUE, main="Classification Tree")
text(modFit$finalModel,use.n=TRUE,all=TRUE,cex=.8)
```
```{r}
fancyRpartPlot(modFit$finalModel)
```

```{r random_forest}
modFit <- train(classe~ .,data=training,method="rf",prox=TRUE)
modFit
```