---
title: "try8"
output: html_document
---

```{r check_libraries,echo=FALSE}
# Check to see if all the packages that are needed are installed and loaded.
# If they aren't installed and/or loaded, load them. As it is not part of the overall model, code will not be revealed here.
require(caret)
require(randomForest)
require(foreach)
require(doParallel)
require(rpart)
require(rattle)

pkgTest <- function(x)
{
  if (!require(x,character.only = TRUE))
  {
    install.packages(x,dependencies = TRUE)
       if(!require(x,character.only = TRUE)) stop("Package not found")
  }
}

library(caret)
library(randomForest)
library(foreach)
library(doParallel)
library(rpart)
library(rattle)
```

```{r load_data}
# Load data. Import if necessary
if (!file.exists("pml-training.csv")) {
  download.file("http://d396qusza40orc.cloudfront.net/predmachlearn/pml-training.csv", 
                destfile = "pml-training.csv")
}
if (!file.exists("pml-testing.csv")) {
  download.file("http://d396qusza40orc.cloudfront.net/predmachlearn/pml-testing.csv", 
                destfile = "pml-testing.csv")
}
```
```{r set_seed}
# Set seed for reproducibility
set.seed(1979)
options(warn=-1)
```
```{r read_data}
# Convert NA,NULL,#DIV/0! when reading in the data
pmlTraining <- read.csv("pml-training.csv", header = TRUE, sep = ",",na.strings=c('NA','','#DIV/0!'))
```

```{r rm_columns_with_mostlyNAs}
naMeanGT95 <- sapply(pmlTraining, function(x) mean(is.na(x))) > 0.95 
pmlTraining <- pmlTraining[, naMeanGT95==F] 
```

```{r nearZeroVariation}
nzv <- nearZeroVar(pmlTraining) 
pmlTraining <- pmlTraining[, -nzv] 
```

```{r split_data_for_training}
# Use partitions to split data into training (60%) and testing (40%)
inTrain <- createDataPartition(y=pmlTraining$classe,p=0.6,list=FALSE)
training <- pmlTraining[inTrain,]  # put data into training
testing <- pmlTraining[-inTrain,]  # put remainder into testing

dim(training)
dim(testing)
```

```{r clean_trim_data}
# Convert columns 8 to end -classe column to numeric
for(i in c(8:ncol(pmlTraining)-1)){
  pmlTraining[,i]=as.numeric(as.character((pmlTraining[,i])))
}
# Remove columns that cannot be processed (not numerical values)
training <- training[, -c(1:7)]
testing <- testing[, -c(1:7)]
# Remove columns (predictors) that contain missing values
training <- training[, colSums(is.na(training))==0]
testing <- testing[, colSums(is.na(training))==0]

dim(training)
dim(testing)
colnames(training)
```

```{r compare_training_types_rpart}
# rpart
rpart_model <- train(classe ~ .,method="rpart",data=training)
print(rpart_model$finalModel)
fancyRpartPlot(rpart_model$finalModel)
```
```{r compare_training_types_rf}
# rf (randomForest) combined with ntree
x <- training[-ncol(training)]
y <- training$classe

rf_model <- foreach(ntree=rep(150, 6), .combine=randomForest::combine, .packages='randomForest') %dopar% {
  randomForest(x, y, ntree=ntree)
}
rf_predict <- predict(rf_model, newdata=training)
confusionMatrix(rf_predict,training$classe)
```