---
title: "test2"
author: "Alasdair Hazen"
date: "January 14, 2016"
output: html_document
---

Data

```{r import_data}
if (!file.exists("pml-training.csv")) {
    download.file("http://d396qusza40orc.cloudfront.net/predmachlearn/pml-training.csv", 
                  destfile = "pml-training.csv")
}
if (!file.exists("pml-testing.csv")) {
    download.file("http://d396qusza40orc.cloudfront.net/predmachlearn/pml-testing.csv", 
                  destfile = "pml-testing.csv")
}
```

```{r process_data}
# set libraries
library(ggplot2)
library(dplyr)
library(caret)

# Read data, while dealing with missing or error data
pmlTraining <- read.csv('pml-training.csv', na.strings = c("NA", "", "#DIV/0!"))
pmlTesting <-  read.csv('pml-testing.csv', na.strings = c("NA", "", "#DIV/0!"))

# Subset data by only taking columns with enough values to consider
# This will allow us to estimate the out-of-sample error
set.seed(9523)
inTrain <- createDataPartition(y=pmlTraining$classe, p=0.7, list=FALSE)
pmlTraining1 <- pmlTraining[inTrain, ]
pmlTraining2 <- pmlTraining[-inTrain, ]

```

